{% set name = "numba-progress" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/numba-progress-{{ version }}.tar.gz
  sha256: f2a0da4840997eac2db47ef026c90f440169007d21c42f16551a3ead0e81fd4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - numba >=0.52
    - tqdm

test:
  imports:
    - numba_progress
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mortacious/numba-progress
  summary: A progress bar implementation for numba functions using tqdm
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - OliverEdy
